### ISSUE TITLE
Fix constraints/positioning on the top bar

### ISSUE THREAD

**Issue by HirdayGupta** [ucladevx/dea-frontend#97]
**Motivation**
Right now, in the development branch, the top bar behaves terribly in terms of positioning itself. This is due to an inherent issue with the way constraints are handled on the top bar and fixing that is the focus of this issue. PS: in case it is unclear, the "top bar" refers to the bar on top of the menu screen with the meal period and date selection options.

**The Task**
Right now there are two _known_ issues with the top bar:
1. It doesn't center itself on phones larger than the iPhone 8 (and sometimes cuts off on smaller phones)
2. As pointed out by @niharmitra at last week's meeting, when the user has bold text enabled, some parts of the top bar get cut off. 

**Some Requirements**
* Familiarize yourself with the some of [SnapKit](http://snapkit.io)'s basic features. It's a Pod that helps with AutoLayout and will prove useful while working on this issue.

**Acceptable Criteria**
* For the first known issue, take a look at the changes in [this commit](https://github.com/ucladevx/Bruin-Bite-iOS/commit/bcc9c42b3690595e7db9766e5e9fa33b6d63e5cd) and essentially replicate them into this branch. (I had made that change in the `light-release` branch which was essentially a bunch of hotfixes to get our app ready for the app store. Some of those changes deserve to be part of our `development` branch. This is one of them.)
* For the second known issue, you're going to have to figure out how to fix it. I think UILabel has a flag to resize text? Check it out.
* Lastly, use this issue to try and find all other issues with the top bar's constraints. Test it out with the different accessibility options allowed by iOS (larger font sizes, bold text, etc) and on all possible devices (from iPhone SE to iPhone XS Max) and ensure its working as intended.

**EDIT:** Forgot to mention: Check out the [contributing guide](https://github.com/ucladevx/Bruin-Bite-iOS/wiki/Contribution-Guide) for the git/github workflow we'd like to follow.

**Comment by niharmitra** [comment]
The feature I have enabled isn't Bold Text, its Display Zoom -> View Zoomed, so UI elements are enlarged, not just font size.

**Comment by HirdayGupta** [comment]
Thanks for the clarification, @niharmitra! 
@sahenrai keep that in mind while working on this.

**Comment by HirdayGupta** [comment]
@sahenrai Can confirm that [the commit](https://github.com/ucladevx/Bruin-Bite-iOS/commit/bcc9c42b3690595e7db9766e5e9fa33b6d63e5cd) I was talking about that solves the first known issue is present in development. Focus on solving the second one - and feel free to use the storyboard flag you were talking about. Looking forward to a pull request soon, this task is a week overdue!

**Comment by sahenrai** [comment]
Issue already fixed in development
